### ISSUE TITLE
`Could not get unknown property 'pluginBundle'` (Gradle 8)

### ISSUE THREAD

**Issue by joffrey-bion** [xvik/gradle-github-info-plugin#2]
Since the 1.0 release of the plugin-publish plugin, we should no longer use the `pluginBundle` block. When upgrading to Gradle 8, the Github info plugin fails with:

```
A problem occurred configuring root project 'gradle-kotlin-publish-plugin'.
> Could not get unknown property 'pluginBundle' for root project 'gradle-kotlin-publish-plugin' of type org.gradle.api.Project.

[...]

Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'pluginBundle' for root project 'gradle-kotlin-publish-plugin' of type org.gradle.api.Project.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
	at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:124)
	at ru.vyarus.gradle.plugin.github.configurer.PluginPublishConfigurer$_configure_closure1$_closure2.doCall(PluginPublishConfigurer.groovy:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
	at org.gradle.api.Project$configure$0.call(Unknown Source)
	at ru.vyarus.gradle.plugin.github.configurer.PluginPublishConfigurer$_configure_closure1.doCall(PluginPublishConfigurer.groovy:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at ru.vyarus.gradle.plugin.github.configurer.PluginPublishConfigurer.configure(PluginPublishConfigurer.groovy:26)
	at ru.vyarus.gradle.plugin.github.GithubInfoPlugin$_apply_closure1.doCall(GithubInfoPlugin.groovy:38)
```

I am opening this issue for tracking, but I see you have already committed something along those lines, so thanks!
I'm eagerly waiting for a release with the fix, as I cannot upgrade to Gradle 8 at the moment because of this.

**Comment by xvik** [comment]
[released](https://github.com/xvik/gradle-github-info-plugin/releases/tag/1.5.0)
